// ==UserScript==
// @name         __APP_NAME__
// @namespace    http://tampermonkey2.net/
// @version      __APP_VERSION__
// @description  任意网页提供漫画搜索；漫画分章节下载(可直接下载/压缩下载/拼接下载)，可用于动漫之家、极速漫画、腾讯漫画、哔哩哔哩等35多个网站；对个别漫画网站修改阅读样式；可按需编写定义规则JSON导入以支持其他漫画网站
// @author       journey3510
// @run-at       document-end
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_setClipboard
// @grant        GM_info
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// @grant        GM_getResourceText
// @grant        GM_download
// @grant        GM_registerMenuCommand
// @grant        unsafeWindow
// @resource   vantcss   https://unpkg.com/vant@2.12/lib/index.css
// @require      https://unpkg.com/vue@2.6.12/dist/vue.min.js
// @require      https://unpkg.com/vant@2.12/lib/vant.min.js
// @require      https://unpkg.com/jszip@3.7.1/dist/jszip.min.js
//
// @connect      kumw7.com
// @connect      darpou.com
// @connect      manga8.xyz
// @connect      wuxiamh.com
// @connect      169gouwu.com
// @connect      idmzj.com
// @connect      dmzj.com
// @connect      qiximh2.com
// @connect      byteimg.com
// @connect      arc-theday.com
// @connect      gufengmh.com
// @connect      123gf.com
// @connect      xiaoqinre.com
// @connect      bdstatic.com
// @connect      ac.qq.com
// @connect      acimg.cn
// @connect      mhxqiu1.com
// @connect      byteimg.com
// @connect      haoman8.com
// @connect      mh5.org
// @connect      xiaomingtaiji.net
// @connect      2mzx.com
// @connect      hnsrht.com
// @connect      huayingrenren.cn
// @connect      zuimh.com
// @connect      pinmh.com
// @connect      ejujiu.com
// @connect      dodomh.com
// @connect      qianwee.com
// @connect      szssjg.com
// @connect      ixmh7.com
// @connect      byteimg.com
// @connect      mhxin.com
// @connect      baozimh.com
// @connect      webmota.com
// @connect      kingwar.cn
// @connect      aiguoman.com
// @connect      acgn.cc
// @connect      77mh.xyz
// @connect      dm365.top
// @connect      txydd.com
// @connect      qdjljy.com
// @connect      cnanjie.com
// @connect      maofly.com
// @connect      mhtupian.com
// @connect      bilibili.com
// @connect      hdslb.com
// @connect      mangabz.com
// @connect      qiman59.com
// @connect      dcarimg.com
// @connect      1kkk.com
// @connect      cdndm5.com
// @connect      dm5.com
// @connect      bilibilicomics.com
// @connect      kuaikanmanhua.com
// @connect      v3mh.com
// @connect      kuaikanmanhua.com
// @connect      dongmanmanhua.cn
// @connect      laimidao.com
// @connect      izhegu.com
// @connect      nicefee.com
// @connect      dcarimg.com
// @connect      baozimh.com
// @connect      pstatic.net
// @connect      komiic.com
// @connect      newtoki15.org
// @connect      kanbook.net
// @connect      cdndm5.com
// @license      GPLv3
// @include      *
// @connect      *
// ==/UserScript==
